name: Reusable Workflow user
  
on:
  workflow_dispatch
jobs:
  do-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world-Looking Good11!

  build-called:
      uses: ./.github/workflows/build.yaml
  deploy-called:
    uses: ./.github/workflows/deploy.yml
    needs: build-called
